name: CMake and sanitizers CI

on: [push, pull_request]

jobs:
  ctest:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Download submodule
      run: git submodule update --init
    - name: Create build folder
      run: mkdir build
    - name: Compile
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: build
      run: ctest -V
